# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'taskPlanner' do
  pod 'RxSwift'
    pod 'RxCocoa'
pod 'RxDataSources'


  # Pods for taskPlanner

  target 'taskPlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'taskPlannerUITests' do
    # Pods for testing
pod 'RxBlocking'
    pod 'RxTest'
pod 'RxDataSources' 

  end

end
